# Data Cleaning

In [2]:
import pandas as pd 

df = pd.read_csv("../data/raw/Google-Playstore.csv")

In [3]:
df.shape

(2312944, 24)

### Creating a working copy:

In [4]:
df_clean = df.copy()

In [5]:
df_clean.shape

(2312944, 24)

In [6]:
df_clean.loc[
    df_clean["Installs"].isna(),
    ["App Name", "App Id", "Installs", "Minimum Installs", "Maximum Installs"]
]

,App Name,App Id,Installs,Minimum Installs,Maximum Installs
5622,Claire’s Café: Tasty Cuisine 🥞🧁🍔,com.gamehouse.cc1,NaN,NaN,1023
43569,Potato Smash,com.igg.android.projectpotato,NaN,NaN,72087
60888,SketchBook : Draw Art & Paints,com.sketchbook.illustrations,NaN,NaN,2
64322,Shared grocery Shopping List,com.tikamori.shoppinglist,NaN,NaN,0
91391,NBA NOW 21,com.com2us.nbanow2.android.google.global.normal,NaN,NaN,2
...,...,...,...,...,...
2161180,DEEMO II,com.rayark.deemo2,NaN,NaN,0
2170210,Lendor - Share & Rent Anything!,sg.lendor,NaN,NaN,5178
2205663,Local 24h Motorista,com.movi24h.motorista,NaN,NaN,3238
2212570,Mitrasphere,com.jetsynthesys.mitrasphere,NaN,NaN,13653
2311821,DreamWorks Universe of Legends,com.firefly.dreamworks.dwuol,NaN,NaN,292415

In [7]:
df_clean.loc[
    df_clean["Installs"].isna(),
    ["Minimum Installs", "Maximum Installs"]
].describe()

       Minimum Installs  Maximum Installs
count               0.0      1.070000e+02
mean                NaN      7.346040e+04
std                 NaN      4.031393e+05
min                 NaN      0.000000e+00
25%                 NaN      1.000000e+00
50%                 NaN      5.770000e+02
75%                 NaN      1.437700e+04
max                 NaN      3.755785e+06

In [8]:
# Check the rows first
df_clean[df_clean["App Name"].isna()]

,App Name,App Id,Category,Rating,Rating Count,Installs,Minimum Installs,Maximum Installs,Free,Price,...,Developer Website,Developer Email,Released,Last Updated,Content Rating,Privacy Policy,Ad Supported,In App Purchases,Editors Choice,Scraped Time
45686,NaN,se.promedia.NA,News & Magazines,2.4,470.0,"50,000+",50000.0,84097,True,0.0,...,https://www.na.se/app,kundservice.bnlo@bonniernews.se,"Aug 8, 2011","Dec 21, 2020",Everyone,https://www.na.se/info/mittmedias-personuppgif...,True,False,False,2021-06-15 21:04:54
1226953,NaN,com.ibrahimtornado.none,Entertainment,4.6,11.0,100+,100.0,351,True,0.0,...,NaN,ibra.ibrahim9995@gmail.com,"Mar 22, 2019","Mar 23, 2019",Everyone,https://sites.google.com/view/noneapp/privacy-...,True,False,False,2021-06-15 21:05:32
1712582,NaN,com.noone,Entertainment,4.1,40.0,"1,000+",1000.0,2406,True,0.0,...,NaN,friedchikanye@gmail.com,"Oct 6, 2014","Oct 06, 2014",Everyone,NaN,False,False,False,2021-06-16 04:21:25
1924265,NaN,com.DN.None,Arcade,4.6,5.0,10+,10.0,27,True,0.0,...,NaN,nguyenthaiphihungnew@outlook.com,"Dec 30, 2019","Jan 06, 2020",Everyone,NaN,True,False,False,2021-06-16 07:19:47
2117918,NaN,com.Tomkii.NULl,Arcade,4.3,6.0,50+,50.0,98,True,0.0,...,NaN,tomek.rybinski@interia.pl,"Mar 17, 2021","Mar 17, 2021",Everyone,NaN,True,False,False,2021-06-16 10:09:12

### Observation

The missing `App Name` values do not materially impact the overall analysis, so these records will be retained.

In [9]:
df_clean.drop(columns=["Scraped Time"], inplace=True)

In [10]:
df_clean.columns

Index(['App Name', 'App Id', 'Category', 'Rating', 'Rating Count', 'Installs',
       'Minimum Installs', 'Maximum Installs', 'Free', 'Price', 'Currency',
       'Size', 'Minimum Android', 'Developer Id', 'Developer Website',
       'Developer Email', 'Released', 'Last Updated', 'Content Rating',
       'Privacy Policy', 'Ad Supported', 'In App Purchases', 'Editors Choice'],
      dtype='str')

### Observation

`Scraped Time` was removed because it is a data collection timestamp and does not contribute to the business analysis.

## Date Conversion

In [11]:
date_columns = ["Released", "Last Updated"]

for col in date_columns:
    df_clean[col] = pd.to_datetime(df_clean[col], errors="coerce")

In [12]:
df_clean[date_columns].dtypes

Released        datetime64[us]
Last Updated    datetime64[us]
dtype: object

### Action Performed

Date columns were successfully converted to datetime format.